### ISSUE TITLE
Broken links found on 30 sept 2024

### ISSUE THREAD

**Issue by gbossert** [SEKOIA-IO/documentation#2030]
### Found broken link in https://docs.sekoia.io/stylesheets/lightgallery.min.css
- [x] Link '' that points on https://docs.sekoia.io/fonts/lg.ttf?22t19m) is broken (404 Not Found)
- [x] Link '' that points on https://docs.sekoia.io/fonts/lg.woff?22t19m) is broken (404 Not Found)
- [x] Link '' that points on https://docs.sekoia.io/fonts/lg.svg?22t19m#lg) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/getting_started/
- [ ] **all the links from the TIP section to the automate - actions**
- [ ] Link 'Bitsight SPM' that points on https://docs.sekoia.io/docs/integration/categories/network_security/bitsight_spm.md) is broken (404 Not Found)
- [ ] Link 'Microsoft Entra ID (Azure AD)' that points on https://docs.sekoia.io/integration/action_library/iam/intra-id.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/
- [x] Link 'ingestion methods' that points on https://docs.sekoia.io/xdr/features/collect/ingestion_methods/index.md) is broken (404 Not Found)
- [x] Link 'Integrations' that points on https://docs.sekoia.io/xdr/features/collect/integrations/index.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/stylesheets/inter.min.css
- [x] Link '' that points on https://docs.sekoia.io/assets/fonts/Inter-thin.ttf) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/getting_started/account_security/
- [x] Link 'process' that points on https://support.sekoia.io/hc/en-gb/articles/10904006738845-Request-a-2FA-reset) is broken (403 Forbidden)

### Found broken link in https://docs.sekoia.io/getting_started/sso/openid_connect/
- [x] Link 'Invite users' that points on https://docs.sekoia.io/getting_started/sso/openid_connect/invite_users.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/getting_started/invite_users/
- [x] Link 'create custom roles' that points on https://docs.sekoia.io/getting_started/invite_users/docs/getting_started/roles.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/getting_started/best_practices/
- [ ] Link 'Sekoia.io activity logs' that points on https://docs.sekoia.io/integration/integrations/application/sekoiaio_activity_logs/) is broken (404 Not Found)
- [ ] Link 'Read JSON File' that points on https://docs.sekoia.io/xdr/features/automate/library/fileutils/#read-json-file) is broken (404 Not Found)
- [ ] Link 'Comment Alert' that points on https://docs.sekoia.io/xdr/features/automate/library/sekoia-io/#comment-alert) is broken (404 Not Found)
- [ ] Link 'Request URL' that points on https://docs.sekoia.io/xdr/features/automate/library/http/#request-url) is broken (404 Not Found)
- [ ] Link 'VirusTotal Scan URL' that points on https://docs.sekoia.io/xdr/features/automate/library/virustotal/#scan-url) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/getting_started/get_troubleshooting_tips/
- [x] Link 'app.sekoia.io/live' that points on https://docs.sekoia.io/getting_started/get_troubleshooting_tips/app.sekoia.io/live) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/xdr_quick_start/
- [x] Link 'integrations catalog' that points on https://docs.sekoia.io/integration/integrations/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/features/collect/intakes/
- [x] Link 'integrations' that points on https://docs.sekoia.io/xdr/features/collect/intakes/integrations/index.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/features/automate/playbooks-on-premises/
- [x] Link 'dedicated agent' that points on https://docs.sekoia.io/integration/integrations/endpoint/sekoiaio/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/features/automate/navigate-playbooks/
- [x] Link 'Library section' that points on https://docs.sekoia.io/xdr/features/automate/library/aws/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/features/automate/actions/
- [ ] Link 'Mandrill' that points on https://docs.sekoia.io/integration/action_library/applicative/mandrill.md) is broken (404 Not Found)
- [ ] Link 'Mattermost' that points on https://docs.sekoia.io/integration/action_library/applicative/mattermost.md) is broken (404 Not Found)
- [ ] Link 'Pagerduty' that points on https://docs.sekoia.io/integration/action_library/applicative/pagerduty.md) is broken (404 Not Found)
- [ ] Link 'The Hive' that points on https://docs.sekoia.io/integration/action_library/collaboration_tools/the-hive.md) is broken (404 Not Found)
- [ ] Link 'BinaryEdge' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/binaryedge-s-api.md) is broken (404 Not Found)
- [ ] Link 'Censys' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/censys.md) is broken (404 Not Found)
- [ ] Link 'GLIMPS' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/glimps.md) is broken (404 Not Found)
- [ ] Link 'IKnowWhatYouDownloaded' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/iknowwhatyoudownload.md) is broken (404 Not Found)
- [ ] Link 'Onyphe' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/onyphe.md) is broken (404 Not Found)
- [ ] Link 'Public Suffix' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/public-suffix.md) is broken (404 Not Found)
- [ ] Link 'RiskIQ' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/riskiq.md) is broken (404 Not Found)
- [ ] Link 'Shodan' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/shodan.md) is broken (404 Not Found)
- [ ] Link 'VirusTotal' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/virustotal.md) is broken (404 Not Found)
- [ ] Link 'Whois' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/whois.md) is broken (404 Not Found)
- [ ] Link 'fileutils' that points on https://docs.sekoia.io/integration/action_library/generic/fileutils.md) is broken (404 Not Found)
- [ ] Link 'http' that points on https://docs.sekoia.io/integration/action_library/generic/http.md) is broken (404 Not Found)
- [ ] Link 'STIX' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/stix.md) is broken (404 Not Found)
- [ ] Link 'MISP' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/misp.md) is broken (404 Not Found)
- [ ] Link 'MWDB' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/mwdb.md) is broken (404 Not Found)
- [ ] Link 'Triage' that points on https://docs.sekoia.io/integration/action_library/threat_intelligence/triage.md) is broken (404 Not Found)
- [ ] Link 'Microsoft Entra ID (Azure AD)' that points on https://docs.sekoia.io/integration/action_library/iam/microsoft-entra-id.md) is broken (404 Not Found)
- [ ] Link 'Microsoft Remote Server' that points on https://docs.sekoia.io/integration/action_library/applicative/microsoft-remote-server.md) is broken (404 Not Found)
- [ ] Link 'Fortigate Firewalls' that points on https://docs.sekoia.io/integration/action_library/network/fortigate-firewalls.md) is broken (404 Not Found)
- [ ] Link 'HarfangLab' that points on https://docs.sekoia.io/integration/action_library/endpoint/harfanglab.md) is broken (404 Not Found)
- [ ] Link 'Panda Security' that points on https://docs.sekoia.io/integration/action_library/endpoint/panda-security.md) is broken (404 Not Found)
- [ ] Link 'Sentinel One' that points on https://docs.sekoia.io/integration/action_library/endpoint/sentinelone.md) is broken (404 Not Found)
- [ ] Link 'ServiceNow' that points on https://docs.sekoia.io/integration/action_library/collaboration_tools/servicenow.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/usecases/playbook/synchronize_alerts/
- [ ] Link 'Custom format Intake' that points on https://docs.sekoia.io/integration/develop_integration/formats/create_a_format.md) is broken (404 Not Found)
- [ ] Link 'documentation' that points on https://docs.sekoia.io/xdr/usecases/features/automate/library/http.md#request-url) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/xdr/develop/rest_api/quickstart/
- [ ] Link 'filtering' that points on https://docs.sekoia.io/xdr/develop/guides/filtering/) is broken (404 Not Found)
- [ ] Link 'how to create automation modules' that points on https://docs.sekoia.io/xdr/develop/guides/automation/overview/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/cti/features/consume/intelligence/
- [ ] Link 'this page' that points on https://docs.sekoia.io/_shared_content/intelligence_center/data_model.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/ingestion_methods/https/logstash/
- [ ] Link 'Beats (Winlogbeat)' that points on https://docs.sekoia.io/integration/integrations/endpoint/winlogbeat.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/overview/
- [ ] Link 'Best Practices for Using Sekoia SOC Platform page' that points on https://docs.sekoia.io/integration/categories/overview/getting_started/best_practices/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/applicative/cloudflare-audit-logs/
- [ ] Link 'Cloudflare Console' that points on https://dash.cloudflare.com/) is broken (403 Forbidden)

### Found broken link in https://docs.sekoia.io/integration/categories/applicative/azure_files/
- [ ] Link 'Consume Eventhub messages' that points on https://docs.sekoia.io/xdr/feature/automate/library/microsoft-azure/#consume-eventhub-messages) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/azure_windows/
- [ ] Link 'Microsoft Github windows diagnostic extension documentation' that points on https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/platform/diagnostics-extension-stream-event-hubs.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/cybereason_malop/
- [ ] Link 'Fetch new events from Cybereason' that points on https://docs.sekoia.io/integration/action_library/endpoint/cybereason.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/eset_protect/
- [ ] Link 'how to secure data collection to the syslog forwarder' that points on https://docs.sekoia.io/integration/categories/endpoint/eset_protect/intergration/ingestion_methods/syslog/secured_forwarded.md) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/kaspersky_endpoint_security/
- [ ] Link 'kaspersky_endpoint_security_architecture' that points on https://docs.sekoia.io/assets/integration/kaspersky_endpoint_security_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/sentinelone/
- [ ] Link 'SentinelOne playbook actions' that points on https://docs.sekoia.io/xdr/features/automate/library/sentinelone) is broken (404 Not Found)
- [ ] Link 'SentinelOne EDR Intake creation' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/endpoint/sentinelone/sentinelone-configure-intake.png) is broken (404 Not Found)
- [ ] Link 'SentinelOne EDR secret' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/endpoint/sentinelone/sentinelone_edr_api.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/sekoiaio/
- [ ] Link 'https://api.sekoia.io/' that points on https://api.sekoia.io/) is broken (404 Not Found)
- [ ] Link 'SwiftOnSecurity's configuration' that points on https://github.com/SwiftOnSecurity/sysmon-config.md) is broken (404 Not Found)
- [ ] Link 'Configuring Security Log Audit Settings' that points on https://github.com/Yamato-Security/EnableWindowsLogSettings/blob/main/ConfiguringSecurityLogAuditPolicies) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/stormshield_ses/
- [ ] Link 'Agent handlers' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_01.png) is broken (404 Not Found)
- [ ] Link 'Configuration' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_02.png) is broken (404 Not Found)
- [ ] Link 'Certificate store' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_03.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/endpoint/sophos_edr/
- [ ] Link 'Sophos Central APIs: Send alert and event data to your SIEM' that points on https://support.sophos.com/support/s/article/KB-000036372?language=en_US) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/iam/rsa_securid/
- [ ] Link 'How to configure RSA Authentication Manager 8.1, 8.2, 8.3 to send data to multiple remote syslog servers' that points on https://community.rsa.com/t5/securid-knowledge-base/how-to-configure-rsa-authentication-manager-8-1-8-2-8-3-to-send/ta-p/2525) is broken (401 Unauthorized)

### Found broken link in https://docs.sekoia.io/integration/categories/network/arubaos/
- [ ] Link 'ArubaOS documentation' that points on https://www.arubanetworks.com/documentation/) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network/cato_sase/
- [ ] Link 'Cato Networks - Generating API Keys for the Cato API' that points on https://support.catonetworks.com/hc/en-us/articles/4413280536081-Generating-API-Keys-for-the-Cato-API) is broken (403 Forbidden)

### Found broken link in https://docs.sekoia.io/integration/categories/network/efficientip_solidserver_ddi/
- [ ] Link 'Adminstation' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/network/efficientip_solidserver/01%20-%20administration.png) is broken (404 Not Found)
- [ ] Link 'Configuration' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/network/efficientip_solidserver/02%20-%20configuration.png) is broken (404 Not Found)
- [ ] Link 'syslog' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/network/efficientip_solidserver/03%20-%20syslog.png) is broken (404 Not Found)
- [ ] Link 'target' that points on https://docs.sekoia.io/assets/operation_center/integration_catalog/network/efficientip_solidserver/04%20-%20target.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network/forcepoint_web_gateway/
- [x] Link 'forcepoint_swg_architecture' that points on https://docs.sekoia.io/assets/integration/forcepoint_swg_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network/dhcpd/
- [x] Link 'isc_dhcp_architecture' that points on https://docs.sekoia.io/assets/integration/isc_dhcp_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network/pulse/
- [x] Link 'pulse_connect_secure_architecture' that points on https://docs.sekoia.io/assets/integration/pulse_connect_secure_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network_security/claroty_xdome/
- [ ] Link 'About Claroty Syslog' that points on https://help.claroty.com/hc/en-us/articles/10703054977053-About-Claroty-Syslog) is broken (403 Forbidden)

### Found broken link in https://docs.sekoia.io/integration/categories/network_security/fortiproxy/
- [x] Link 'fortinet_fortiproxy_architecture' that points on https://docs.sekoia.io/assets/integration/fortinet_fortiproxy_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network_security/gatewatcher_aioniq/
- [x] Link 'gatewatcher_aioniq_architecture' that points on https://docs.sekoia.io/assets/integration/gatewatcher_aioniq_architecture.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/categories/network_security/sophos_threat_analysis_center/
- [ ] Link 'Windows Requirements' that points on https://support.sophos.com/support/s/article/KB-000035144?language=en_US) is broken (404 Not Found)
- [ ] Link 'Windows Server Requirements' that points on https://support.sophos.com/support/s/article/KB-000034074?language=en_US) is broken (404 Not Found)
- [ ] Link 'MacOS Requirements' that points on https://support.sophos.com/support/s/article/KB-000034670?language=en_US) is broken (404 Not Found)
- [ ] Link 'Identify your region' that points on https://support.sophos.com/support/s/article/KB-000044836?language=en_US) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/action_library/applicative/microsoft-windows-server/
- [x] Link 'Microsoft Windows Server' that points on https://docs.sekoia.io/assets/playbooks/library/microsoft-windows-server.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/action_library/endpoint/trend-micro/
- [x] Link 'Trend Micro' that points on https://docs.sekoia.io/assets/playbooks/library/trend-micro.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/action_library/iam/microsoft-entra-id/
- [x] Link 'Microsoft Entra ID' that points on https://docs.sekoia.io/assets/playbooks/library/microsoft-entra-id.svg) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/action_library/network/cato-networks/
- [x] Link 'Cato Networks' that points on https://docs.sekoia.io/assets/playbooks/library/cato-networks.png) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/develop_integration/automation/action/
- [ ] Link 'Azure Active Directory «Enable User» action’s manifest' that points on https://docs.sekoia.io/integration/develop_integration/automation/AzureActiveDirectory/action_enable_user.json) is broken (404 Not Found)
- [ ] Link 'Azure Active Directory «Enable User» code' that points on https://docs.sekoia.io/integration/develop_integration/automation/AzureActiveDirectory/azure_ad/user.py) is broken (404 Not Found)
- [ ] Link 'Azure Active Directory main.py' that points on https://docs.sekoia.io/integration/develop_integration/automation/AzureActiveDirectory/main.py) is broken (404 Not Found)

### Found broken link in https://docs.sekoia.io/integration/develop_integration/automation/trigger/
- [ ] Link 'OKTA system log connector' that points on https://docs.sekoia.io/integration/develop_integration/automation/Okta/okta_modules/system_log_trigger.py) is broken (404 Not Found)
- [ ] Link 'Okta main.py' that points on https://docs.sekoia.io/integration/develop_integration/automation/Okta/main.py) is broken (404 Not Found)

**Comment by jeromefellus-sekoia** [comment]
There are so much bullet points in this issue, I couldn't check all of them.
I strongly believe https://github.com/SEKOIA-IO/documentation/pull/2093 fixes all the broken **internal** links.

Still it would be cool to extract from your list the external URLs that are broken. I'll post an extract of them a will focus on these.

Feel free to tell me if you need me to individually check all the links one by one instead

**Comment by jeromefellus-sekoia** [comment]
external broken links (excluding *.sekoia.io)

* [ ] https://community.rsa.com/t5/securid-knowledge-base/how-to-configure-rsa-authentication-manager-8-1-8-2-8-3-to-send/ta-p/2525
* [ ] https://dash.cloudflare.com/
* [ ] https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/platform/diagnostics-extension-stream-event-hubs.md
* [ ] https://github.com/SwiftOnSecurity/sysmon-config.md
* [ ] https://github.com/Yamato-Security/EnableWindowsLogSettings/blob/main/ConfiguringSecurityLogAuditPolicies
* [ ] https://help.claroty.com/hc/en-us/articles/10703054977053-About-Claroty-Syslog
* [ ] https://support.catonetworks.com/hc/en-us/articles/4413280536081-Generating-API-Keys-for-the-Cato-API
* [ ] https://support.sophos.com/support/s/article/KB-000034074?language=en_US
* [ ] https://support.sophos.com/support/s/article/KB-000034670?language=en_US
* [ ] https://support.sophos.com/support/s/article/KB-000035144?language=en_US
* [ ] https://support.sophos.com/support/s/article/KB-000036372?language=en_US
* [ ] https://support.sophos.com/support/s/article/KB-000044836?language=en_US
* [ ] https://www.arubanetworks.com/documentation/

**Comment by jeromefellus-sekoia** [comment]
Allow me to close this issue with PR #2093 and open a specific one for those external links (because I think we can handle them automatically, this will be a longer process with manual investigation for each)
