### ISSUE TITLE
Broken link on CTI/Develop guide

### ISSUE THREAD

**Issue by gbossert** [SEKOIA-IO/documentation#2085]
he link in the documentation related to the ["Filtering functionality"](https://docs.sekoia.io/cti/develop/guides/filtering/) is not pointing any related documentation

I got redirected to the error page by clicking on "Filtering" as seen in the first screenshot

![image](https://github.com/user-attachments/assets/f0d99a32-c6f7-4002-852c-c24b268d8c52)
![image](https://github.com/user-attachments/assets/70c2246b-09fd-4031-88ba-4cd57a81b399)

**Comment by gbossert** [comment]
Could be related to this work: https://github.com/SEKOIA-IO/documentation/commit/48b79a52ab0e3a596872f82ea3c2b040648c029b

**Comment by rombernier** [comment]
fix by https://github.com/SEKOIA-IO/documentation/pull/2086
